export const categories = [
    {
        id: "#0001",
        category: "Watch",
        date: "2022-06-01",
        status: "Published",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0002",
        category: "Toy",
        date: "2022-02-01",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0003",
        category: "Laptop",
        date: "2022-02-01",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: {pubDate: "", pubTime: ""} ,
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0004",
        category: "Mobile",
        date: "2022-04-01",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0005",
        category: "Tv",
        date: "2022-04-08",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0006",
        category: "Clothes",
        date: "2022-03-01",
        status: "Published",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0007",
        category: "Footwear",
        date: "2022-03-02",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0008",
        category: "Beautywear",
        date: "2022-01-06",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0009",
        category: "Watch",
        date: "2022-06-01",
        status: "Published",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0010",
        category: "Toy",
        date: "2022-02-01",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0011",
        category: "Laptop",
        date: "2022-02-01",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: {pubDate: "", pubTime: ""} ,
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0012",
        category: "Mobile",
        date: "2022-04-01",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0013",
        category: "Tv",
        date: "2022-04-08",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0014",
        category: "Clothes",
        date: "2022-03-01",
        status: "Published",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0015",
        category: "Footwear",
        date: "2022-03-02",
        status: "Hidden",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
    {
        id: "#0015",
        category: "Beautywear",
        date: "2022-01-06",
        status: "Scheduled",
        visibilityStatus: "",
        pubSch: { pubDate: "", pubTime: "" },
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [] },
    },
];
