export const Coupons = [
    {
        id: 1,
        code: "AXXQT-2547",
        type: "Free",
        discount: "50%",
        startDate: "03/10/2021",
        endDate: "02/1/2021",
        status: "Active",
        discountCountry: "India",
        discountProduct: "Dresses",
        couponLimit: 2,
    },
    {
        id: 2,
        code: "BATTT-XA47",
        type: "Shipping",
        discount: "$18.00",
        startDate: "06/05/2021",
        endDate: "06/09/2021",
        status: "Active",
        discountCountry: "Bangladesh",
        discountProduct: "Plazos",
        couponLimit: 3,
    },
    {
        id: 3,
        code: "DTZQT-8547",
        type: "Discounts",
        discount: "$12.6",
        startDate: "18/08/2021",
        endDate: "06/09/2021",
        status: "In Active",
        discountCountry: "Nepal",
        discountProduct: "Plazos",
        couponLimit: 4,
    },
    {
        id: 4,
        code: "FALT-40",
        type: "Free",
        discount: "$0.0",
        startDate: "18/08/2021",
        endDate: "06/09/2021",
        status: "Active",
        discountCountry: "SriLanka",
        discountProduct: "Plazos",
        couponLimit: 5,
    },
    {
        id: 5,
        code: "FiFty-50%",
        type: "Shipping",
        discount: "50%",
        startDate: "16/04/2021",
        endDate: "06/09/2021",
        status: "Future Plan",
        discountCountry: "NewZeaLand",
        discountProduct: "Plazos",
        couponLimit: 6,
    },
    {
        id: 6,
        code: "SHIP-ZERO",
        type: "Discounts",
        discount: "18%",
        startDate: "18/08/2021",
        endDate: "06/09/2021",
        status: "In Active",
        discountCountry: "Denmark",
        discountProduct: "Plazos",
        couponLimit: 7,
    },
];
