export const Customers = [
    {
        id: "#Order-1100",
        item: "Note Diaries",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-3.jpg",
        category: "kids",
        customer: "Gabrielle",
        email: "gabrielle@gmail.com",
        phone: "7892618561",
        country: "Denmark",
        payment: "Debit card",
        paymentinfo: "Credit card",
        price: "$1000",
        order: "363",
        orderdate: "02/012/2021",
        status: "completed",
    },

    {
        id: "#Order-1101",
        item: "Wall Clock",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-2.jpg",
        category: "women",
        customer: "Alexander",
        email: "Alexander@gmail.com",
        phone: "9261856134",
        country: "Srilanka",
        payment: "UPI",
        paymentinfo: "Debit card",
        price: "$500",
        order: "35",
        orderdate: "12/12/2021",
        status: "progress",
    },
    {
        id: "#Order-1102",
        item: "Lehenga",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        category: "women",
        email: "adam763@gmail.com",
        phone: "7892618565",
        country: "India",
        customer: "Adam H",
        payment: "Credit card",
        paymentinfo: "Credit card",
        price: "$2500",
        order: "514",
        orderdate: "02/02/2022",
        status: "progress",
    },
    {
        id: "#Order-1103",

        item: "Top",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        category: "kids",
        customer: "Sonia",
        email: "Soniaa@gmail.com",
        phone: "8926185616",
        country: "Singapore",
        payment: "Amazon Pay",
        paymentinfo: "Debit Card",
        price: "$500",
        order: "213",
        orderdate: "19/02/2022",
        status: "completed",
    },
    {
        id: "#Order-1104",
        item: "Dhoti Pant",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        category: "women",
        customer: "Julia",
        email: "Julia@gmail.com",
        phone: "9261856122",
        country: "Australia",
        payment: "Razor Pay",
        paymentinfo: "Credit Card",
        price: "$1500",
        order: "134",
        orderdate: "19/05/2022",
        status: "completed",
    },
    {
        id: "#Order-1105",
        item: "Dress",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        category: "kids",
        customer: "Brian",
        email: "brian@gmail.com",
        phone: "7292618561",
        country: "USA",
        payment: "Paytm",
        paymentinfo: "Bank EMI",
        price: "$500",
        order: "434",
        orderdate: "19/05/2021",
        status: "completed",
    },
];
