export const orders = [
    {
        id: "#Order-11414",
        item: "Note Diaries",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-3.jpg",
        customer: "Gabrielle",
        billingdate: "12/01/2021",
        payment: "Debit card",
        price: "$1000",
        quantity: "1",
        status: "delivered",
    },
    {
        id: "#Order-18414",
        item: "Oculus VR",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        customer: "Alexander",
        billingdate: "12/09/2021",
        payment: "UPI",
        price: "$500",
        quantity: "2",
        status: "inprocess",
    },
    {
        id: "#Order-28414",
        item: "Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-2.jpg",
        customer: "Karishma",
        billingdate: "12/05/2021",
        payment: "Credit card",
        price: "$2500",
        quantity: "1",
        status: "delivered",
    },
    {
        id: "#Order-38414",
        item: "Watch",
        img: "https://m.media-amazon.com/images/I/81nC4u9eYfL._UY445_.jpg",
        customer: "Sanskriti",
        billingdate: "03/05/2021",
        payment: "Amazon Pay",
        price: "$500",
        quantity: "3",
        status: "inprocess",
    },
    {
        id: "#Order-484144",
        item: "Flower Port",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-4.jpg",
        customer: "Rose",
        billingdate: "12/03/2021",
        payment: "Razor Pay",
        price: "$1500",
        quantity: "1",
        status: "inprocess",
    },
    {
        id: "#Order-58414",
        item: "Laptop",
        img: "https://m.media-amazon.com/images/I/41vbmwe7e4L._SY450_.jpg",
        customer: "Shreya",
        billingdate: "19/05/2021",
        payment: "Paytm",
        price: "$500",
        quantity: "1",
        status: "inprocess",
    },
];
