export const Products = [
    {
        id: 1,
        item: "Oculus VR",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        Reference: "11110",
        payment: "Debit card",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 2,
        item: "Wall Clock",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-2.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 3,
        item: "Note Diaries",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-3.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 4,
        item: "Flower Port",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-4.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 5,
        item: "School Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-5.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 6,
        item: "Rado Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-6.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 6,
        item: "TRavelling Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-7.jpg",
        Reference: "11110",
        priceends: "20:46",
        price: "149",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "",
        totalStockQty: "",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
];
