export const products = [
    {
        id: 1,
        item: "Oculus VR",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        Reference: "11110",
        payment: "Debit card",
        customer: "Joan Dyer",
        priceends: "20:46",
        price: "149",
        date: "June 23, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Gaming Accessories",
        totalStockQty: "1455",
        instock: "300",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },

    {
        id: 2,
        item: "Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-2.jpg",
        Reference: "11110",
        priceends: "20:46",
        customer: "Robert Anderson",
        price: "149",
        date: "	June 22, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Watch",
        totalStockQty: "4444",
        instock: "4000",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 3,
        item: "Note Diaries",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-3.jpg",
        Reference: "11110",
        priceends: "20:46",
        customer: "Sally Graham",
        price: "149",
        date: "	June 18, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Toy",
        totalStockQty: "2489",
        instock: "2489",
        status: "out of stock",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 4,
        item: "Flower Port",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-4.jpg",
        Reference: "11110",
        customer: "Darwin Chhetri",
        priceends: "20:46",
        price: "149",
        date: "	August 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Toy",
        totalStockQty: "2000",
        instock: "1980",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 5,
        item: "School Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-5.jpg",
        Reference: "11110",
        customer: "Victor Rampling",
        priceends: "20:46",
        price: "149",
        date: "	October 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Bags",
        totalStockQty: "200",
        instock: "99",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 6,
        item: "Rado Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-6.jpg",
        Reference: "11110",
        customer: "Ryan Randall",
        priceends: "20:46",
        price: "149",
        date: "November 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Watch",
        totalStockQty: "700",
        instock: "489",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 7,
        item: "Travelling Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-7.jpg",
        Reference: "11110",
        customer: "Phil Glover",
        priceends: "20:46",
        price: "149",
        date: "	September 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Bags",
        totalStockQty: "370",
        instock: "248",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
];
