export const Stocks = [
    {
        id: 1,
        item: "Oculus VR",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-1.jpg",
        Reference: "11110",
        payment: "Debit card",
        customer: "Joan Dyer",
        priceends: "20:46",
        price: "149",
        date: "June 23, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Gaming Accessories",
        totalStockQty: "1455",
        instock: "300",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },

    {
        id: 2,
        item: "Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-2.jpg",
        Reference: "11110",
        priceends: "20:46",
        customer: "Robert Anderson",
        price: "149",
        date: "	June 22, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Watch",
        totalStockQty: "4444",
        instock: "4000",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 3,
        item: "Note Diaries",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-3.jpg",
        Reference: "11110",
        priceends: "20:46",
        customer: "Sally Graham",
        price: "149",
        date: "	June 18, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Toy",
        totalStockQty: "2489",
        instock: "2489",
        status: "out of stock",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 4,
        item: "Flower Port",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-4.jpg",
        Reference: "11110",
        customer: "Darwin Chhetri",
        priceends: "20:46",
        price: "149",
        date: "	August 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Toy",
        totalStockQty: "2000",
        instock: "1980",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 5,
        item: "School Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-5.jpg",
        Reference: "11110",
        customer: "Victor Rampling",
        priceends: "20:46",
        price: "149",
        date: "	October 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Bags",
        totalStockQty: "200",
        instock: "99",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 6,
        item: "Rado Watch",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-6.jpg",
        Reference: "11110",
        customer: "Ryan Randall",
        priceends: "20:46",
        price: "149",
        date: "November 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Watch",
        totalStockQty: "700",
        instock: "489",
        status: "Offer process",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
    {
        id: 7,
        item: "Travelling Bag",
        img: "https://www.pixelwibes.com/template/ebazar/html/dist/assets/images/product/product-7.jpg",
        Reference: "11110",
        customer: "Phil Glover",
        priceends: "20:46",
        price: "149",
        date: "	September 28, 2022",
        offer: "Bank Offer",
        ratings: "4.5(77)",
        pricingInfo: { productPriceOld: "", productPriceNew: "", coupon: "" },
        visibilityStatus: "",
        size: [],
        pubSch: { pubDate: "", pubTime: "" },
        category: "Bags",
        totalStockQty: "370",
        instock: "248",
        status: "sell",
        basicInfo: { name: "", pageTitle: "", description: "" },
        fileUpload: { productImg: [], patternImg: [], threeDModel: "" },
    },
];
export const department = [
    {
        id: 1,

        head: "Joan Dyer",
        name: "Logistics",
        staff: "40",
    },
    {
        id: 2,

        head: "Ryan Randall",
        name: "Digital Marketing",
        staff: "48",
    },
    {
        id: 3,

        head: "Phil Glover",
        name: "Customer Service",
        staff: "15",
    },
    {
        id: 4,

        head: "Victor Rampling",
        name: "Inventory Associates",
        staff: "40",
    },
    {
        id: 5,

        head: "Sally Graham",
        name: "Finance and Accounting",
        staff: "39",
    },
    {
        id: 6,

        head: "Robert Anderson",
        name: "Business Analyst",
        staff: "12",
    },
    {
        id: 7,

        head: "Ema Board",
        name: "Sales Executive",
        staff: "90",
    },
];
export const suppliers = [
    {
        id: "#SP-00001",
        item: "cloth",
        name: "Joan Dyer",
        regdate: "25/02/2021",
        mail: "VictorRampling@gmail.com",
        phone: "404-555-0100",
        staff: "40",
    },
    {
        id: "#SP-00002",
        item: "cycle",
        name: "Ryan Randall",
        regdate: "18/01/2021",
        mail: "RobertAnderson@gmail.com",
        phone: "502-555-0133",
        staff: "48",
    },
    {
        id: "#SP-00003",
        item: "Shoes",
        name: "Phil Glover",
        regdate: "16/03/2021",
        mail: "PhilGlover@gmail.com",
        phone: "843-555-0175",
        staff: "15",
    },
    {
        id: "#SP-00004",
        item: "Oil",
        name: "Victor Rampling",
        regdate: "16/02/2021",
        mail: "Victor@gmail.com",
        phone: "502-555-0118",
        staff: "40",
    },
    {
        id: "#SP-00005",
        item: "Sunglasses",
        name: "Sally Graham",
        regdate: "12/03/2021",
        mail: "Sally@gmail.com",
        phone: "504-555-0100",
        staff: "39",
    },
    {
        id: "#SP-00006",
        item: "Laptop",
        name: "Robert Anderson",
        regdate: "12/03/2021",
        mail: "Robert@gmail.com",
        phone: "604-555-0100",
        staff: "12",
    },
    {
        id: "#SP-00007",
        item: "Watch",
        name: "Ema Board",
        regdate: "12/08/2021",
        mail: "Ema@gmail.com",
        phone: "502-559-0118",
        staff: "90",
    },
];
export const purchase = [
    {
        id: "#PR-00001",
        item: "cloth",
        name: "Joan Dyer",
        date: "12/11/2022",
        supplier: "Cloth supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "3 Month",
        status: "Item Received",
    },
    {
        id: "#PR-00002",
        item: "cycle",
        name: "Ryan Randall",
        date: "19/01/2023",
        supplier: "Cycle supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "6 Month",
        status: "Item Received",
    },
    {
        id: "#PR-00003",
        item: "Shoes",
        name: "Phil Glover",
        date: "12/03/2021",
        supplier: "Shoes supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "5 Month",
        status: "Item Received",
    },
    {
        id: "#PR-00004",
        item: "Oil",
        name: "Victor Rampling",
        date: "12/10/2022",
        supplier: "Oil supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "4 month",
        status: "Item Received",
    },
    {
        id: "#PR-00005",
        item: "Sunglasses",
        date: "12/01/2023",
        name: "Sally Graham",
        supplier: "Sunglasses supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "2 Month",
        status: "Item Received",
    },
    {
        id: "#PR-00006",
        item: "Watch",
        name: "Robert Anderson",
        date: "12/09/2022",
        supplier: "Watch supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "5 Month",
        status: "Item Received",
    },
    {
        id: "#PR-00007",
        item: "Laptop",
        name: "Ema Board",
        date: "12/03/2022",
        supplier: "Laptop supplier",
        total: "$1551",
        paid: "$1500",
        balance: "$51",
        credit: "8 Month",
        status: "Item Received",
    },
];
